django/data/eventplanning/urls.py
from django.urls import path, re_path

from . import views

app_name = 'eventplanning'
urlpatterns = [
    path('home', views.home, name='home'),
    path('plan', views.plan, name='plan'),
    re_path(r'^del/event/(?P<id>.+)$', views.deleteEvent, name='delevent'),
    re_path(r'^edit/event/(?P<id>.+)$', views.editEvent, name='editevent'),
    re_path(r'^att/event/(?P<id>.+)$', views.attendEvent, name='attevent'),
    re_path(r'^attedit/event/(?P<id>.+)$', views.editAttendance, name='attedit'),
    re_path(r'^leave/event/(?P<id>.+)$', views.leaveEvent, name='leaveevent'),
]

django/data/project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = 'root'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('admin/', admin.site.urls),
    path('acc/', include('accounting.urls')),
    path('auth/', include('authentication.urls')),
    path('event/', include('eventplanning.urls')),
    path('route/', include('routing.urls')),
    path('usr/', include('usermanagement.urls'))
]

django/data/routing/urls.py
from django.urls import path, re_path

from . import views

app_name = 'routing'
urlpatterns = [
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)/(?P<passengerId>.+)$', views.deletePassenger, name='delpass'),
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)$', views.deleteVehicle, name='delcar'),
    re_path(r'^create/(?P<eventId>.+)$', views.createRoute, name='createroute'),
    re_path(r'^confirm/(?P<eventId>.+)$', views.confirmRoute, name='confirmroute'),
]

django/data/usermanagement/urls.py
from django.urls import path, re_path

from . import views

app_name = 'usrmgmt'
urlpatterns = [
    path('home', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('changepass', views.changePassword, name='changepass'),
    re_path(r'^del/addr/(?P<id>.+)$', views.deleteAddress, name='deladdr'),
    re_path(r'^del/grp/(?P<id>.+)$', views.deleteGroup, name='delgrp'),
    re_path(r'^adm/grp/(?P<id>.+)$', views.groupAdmin, name='admgrp'),
]

django/data/usermanagement/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField("authentication.CustomUser", on_delete=models.CASCADE, primary_key=True)
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email

class Address(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    city = models.CharField(max_length=30)
    street = models.CharField(max_length=30)
    postal = models.PositiveIntegerField()
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s, %s %s" % (self.street, self.postal, self.city)

class CommuteGroup(models.Model):
    name = models.CharField(max_length=30)
    member = models.ManyToManyField(Profile, blank=True)
    joinCode = models.CharField(max_length=10, default='None')
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

django/data/project_django/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as signout
from django.contrib import messages

def home(request):
    if request.user.is_anonymous:    
        title = 'Home - Fahrerplanung'
        form = AuthenticationForm()

        dictContext = {'form': form, 'title': title}

        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)

            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')

                user = authenticate(username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect(reverse('home'))
                else:
                    messages.error(request, "Invalid username or password.")
                    return render(request, 'project_django/home.html', dictContext)
            else:
                messages.error(request, "Invalid username or password.")
                return render(request, 'project_django/home.html', dictContext)
        else:
            return render(request, 'project_django/home.html', dictContext)
    elif not request.user.profile.commutegroup_set.all():
        return redirect(reverse('usrmgmt:home'))
    else:
        return redirect(reverse('eventplanning:home'))

def logout(request):
    title = 'Home - Fahrerplanung'
    signout(request)
    
    messages.success(request, "You were successfully logged out.")
    return redirect(reverse('home'))

django/data/project_django/templates/afterLogin.html
<!doctype html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'project_django/styles.css' %}">
        <script src="{% static 'project_django/scripts.js' %}"></script>
        {% block mapsApi %}
            {{ mapsApi|default:"" }}
        {% endblock mapsApi %}
        <meta charset="utf-8">
        <title>
            {% block title %}
            {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>
    </head>

    <body>
        <div class="topnav">
            <a class="left" href="{% url 'eventplanning:home' %}">Events</a>
            <a class="left" href="{% url 'eventplanning:plan' %}">Planning</a>
            <a class="left" href="#Accounting">Accounting</a>
            <a class="left" href="{% url 'usrmgmt:home' %}">User Management</a>
            <a class="right" href="{% url 'logout' %}">Logout</a>
            <a class="right" href="{% url 'usrmgmt:profile' %}">Profile</a>
            {% with user.profile.address_set.all as addresses %}
                {% if not addresses %}
                <a class="tooltip right" href="{% url 'usrmgmt:profile' %}">No Address!
                    <span class="tooltiptext">Tooltip text</span>
                </a>
                {% endif %}
            {% endwith %}
        </div>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}
        <p>Placeholder text in base template. Replace with page content.</p>
        {% endblock content %}
    </body>
</html>

django/data/project_django/templates/beforeLogin.html
<!doctype html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'project_django/styles.css' %}">
        <meta charset="utf-8">
        <title>
            {% block title %}
            {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>
    </head>

    <body>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li  {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}
        <p>Placeholder text in base template. Replace with page content.</p>
        {% endblock content %}
    </body>
</html>