django/data/eventplanning/urls.py
from django.urls import path, re_path

from . import views

app_name = 'eventplanning'
urlpatterns = [
    path('home', views.home, name='home'),
    path('plan', views.plan, name='plan'),
    re_path(r'^del/event/(?P<id>.+)$', views.deleteEvent, name='delevent'),
    re_path(r'^edit/event/(?P<id>.+)$', views.editEvent, name='editevent'),
    re_path(r'^att/event/(?P<id>.+)$', views.attendEvent, name='attevent'),
    re_path(r'^attedit/event/(?P<id>.+)$', views.editAttendance, name='attedit'),
    re_path(r'^leave/event/(?P<id>.+)$', views.leaveEvent, name='leaveevent'),
]

django/data/project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = 'root'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('admin/', admin.site.urls),
    path('acc/', include('accounting.urls')),
    path('auth/', include('authentication.urls')),
    path('event/', include('eventplanning.urls')),
    path('route/', include('routing.urls')),
    path('usr/', include('usermanagement.urls'))
]

django/data/routing/urls.py
from django.urls import path, re_path

from . import views

app_name = 'routing'
urlpatterns = [
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)/(?P<passengerId>.+)$', views.deletePassenger, name='delpass'),
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)$', views.deleteVehicle, name='delcar'),
    re_path(r'^create/(?P<eventId>.+)$', views.createRoute, name='createroute'),
    re_path(r'^confirm/(?P<eventId>.+)$', views.confirmRoute, name='confirmroute'),
]

django/data/eventplanning/models.py
from django.db import models

# Create your models here.

class Event(models.Model):
    name = models.CharField(max_length=30)
    group = models.ForeignKey("usermanagement.CommuteGroup", on_delete=models.CASCADE, null=True)
    eventDate = models.DateField(null=True)
    eventTime = models.TimeField(null=True)
    arrivalTime = models.TimeField(null=True)
    accountedFor = models.BooleanField(default=False)
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Attendee(models.Model):
    user = models.ForeignKey("usermanagement.Profile", on_delete=models.PROTECT)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    address = models.ForeignKey("usermanagement.Address", on_delete=models.PROTECT, null=True)
    isDriver = models.BooleanField(default=False)
    slots = models.PositiveIntegerField(default=0)
    isTaken = models.BooleanField(default=False)
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.user

class Destination(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, primary_key=True)

    city = models.CharField(max_length=30)
    street = models.CharField(max_length=30)
    postal = models.PositiveIntegerField()
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s (%s, %s)" % (self.event.name, self.street, self.city)

django/data/eventplanning/forms.py
from django.apps import apps
from django import forms

from .models import Event, Attendee, Destination
from utils.utils import verifyAddress as verifyAddress

class EventCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        groups = kwargs.pop('groups')
        super(EventCreationForm, self).__init__(*args, **kwargs)
        self.fields['group'] = forms.ModelChoiceField(
            queryset=groups
        )
    class Meta:
        model = Event
        fields = ['group', 'name', 'eventDate', 'eventTime', 'arrivalTime']
        widgets = {
        'eventDate': forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control', 'placeholder':'Select Event date', 'type':'date'}),
        'eventTime': forms.DateInput(format=('%H:%M'), attrs={'class':'form-control', 'placeholder':'Select Event time', 'type':'time'}),
        'arrivalTime': forms.DateInput(format=('%H:%M'), attrs={'class':'form-control', 'placeholder':'Select Arrival time', 'type':'time'}),
        }

    def clean(self):
        # Runs clean() method of ModelForm (parent Class) and verifies for 
        # Uniqueness etc.
        cleaned_data = super(EventCreationForm, self).clean()
        eventTime=cleaned_data.get('eventTime')
        arrivalTime=cleaned_data.get('arrivalTime')

        if arrivalTime > eventTime:
            raise forms.ValidationError(
                "The time of arrival must be equal or earlier than the event start time."
            )

class EventEditForm(EventCreationForm):
    def __init__(self, *args, **kwargs):
        super(EventEditForm, self).__init__(*args, **kwargs)
        self.fields['group'].disabled=True

class AttendeeCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        addrs = kwargs.pop('addrs')
        super(AttendeeCreationForm, self).__init__(*args, **kwargs)
        self.fields['event'].disabled=True
        self.fields['address'] = forms.ModelChoiceField(
            queryset=addrs
        )

    class Meta:
        model = Attendee
        fields = ['event', 'isDriver', 'slots', 'address']

    def clean(self):
        # Runs clean() method of ModelForm (parent Class) and verifies for 
        # Uniqueness etc.
        cleaned_data = super(AttendeeCreationForm, self).clean()
        
        if cleaned_data['isDriver'] and not cleaned_data['slots'] > 0:
            raise forms.ValidationError(
                "If you are a driver, you must have more than 0 slots in your car."
            )

class DestinationCreationForm(forms.ModelForm):
    class Meta:
        model = Destination
        fields = ['city', 'street', 'postal']

    def clean(self):
        # Runs clean() method of ModelForm (parent Class) and verifies for 
        # Uniqueness etc.
        cleaned_data = super(DestinationCreationForm, self).clean()
        
        if not verifyAddress(cleaned_data):
            raise forms.ValidationError(
                "This Address could not be found, please try again with a valid address."
            )

django/data/eventplanning/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.apps import apps
from datetime import date

from .utils import getEditablesForPlanner as eventForPlanner
from .forms import EventCreationForm, EventEditForm, AttendeeCreationForm, DestinationCreationForm
from .models import Event, Attendee

# Create your views here.

@login_required
def home(request):
    title = 'Events'

    groups = request.user.profile.commutegroup_set.all()
    events = Event.objects.filter(group__in=groups, eventDate__gte=date.today())

    signedUpEvents = []

    for event in events:
        for attendee in request.user.profile.attendee_set.all():
            if attendee in event.attendee_set.all() and not event in signedUpEvents:
                signedUpEvents.append(event)

    dictContext = {'title': title, 'events': events, 'signedUpEvents': signedUpEvents}

    return render(request, 'eventplanning/home.html', dictContext)

@login_required
def plan(request):

    title = 'Eventplanning'
    editableEvents = eventForPlanner(request.user, key='events')
    editableGroups = eventForPlanner(request.user, key='groups')
    eventForm = EventCreationForm(groups=editableGroups)
    destForm = DestinationCreationForm()
    dictContext = {'eventForm': eventForm, 'destForm': destForm, 'title': title, 'events': editableEvents}

    if request.method == "POST" and 'newevent' in request.POST:
        eventForm = EventCreationForm(groups=editableGroups, data=request.POST)
        destForm = DestinationCreationForm(data=request.POST)

        if eventForm.is_valid() and destForm.is_valid():
            eventInstance = eventForm.save()
            destInstance = destForm.save(commit=False)

            destInstance.event = eventInstance
            destInstance.save()

            eventRoute = apps.get_model('routing', 'Route')(event=eventInstance)
            eventRoute.save()

            return redirect(reverse('eventplanning:plan'))
        else:
            messages.error(request, "Please enter valid data for the event and destination!\nRemember that the Arrival Time must be equal or earlier than the Event Time!")
            eventForm = EventCreationForm(groups=editableGroups)
            destForm = DestinationCreationForm()
            return render(request, 'eventplanning/plan.html', dictContext)
    
    else:
        return render(request, 'eventplanning/plan.html', dictContext)

@login_required
def deleteEvent(request, id):
    title = 'User Management - Delete Event'
    editableEvents = eventForPlanner(request.user, key='events')
    event = get_object_or_404(Event, id=id)

    dictContext = {'title': title,'event': event}

    if request.method == "POST" and event in editableEvents:
        event.delete()

        messages.success(request, "Event was successfully deleted!")
        return redirect(reverse('eventplanning:plan'))

    elif request.method == "POST":
        messages.error(request, "You do not have permission to delete this event!")
        return redirect(reverse('eventplanning:plan'))

    elif not event in editableEvents:
        messages.error(request, "You do not have permission to delete this event!")
        return redirect(reverse('eventplanning:plan'))

    else:
        return render(request, 'eventplanning/delevent.html', dictContext)

@login_required
def editEvent(request, id):
    title = 'User Management - Edit Event'
    editableEvents = eventForPlanner(request.user, key='events')
    event = get_object_or_404(Event, id=id)
    groupQuerySet = apps.get_model('usermanagement', 'CommuteGroup').objects.filter(event=event.id)
    eventEditForm = EventEditForm(instance=event, groups=groupQuerySet)

    dictContext = {'title': title,'event': event, 'eventEditForm': eventEditForm}

    if request.method == "POST" and event in editableEvents:
        eventEditForm = EventEditForm(instance=event, data=request.POST, groups=groupQuerySet)
        
        if eventEditForm.is_valid():
            editedEvent = eventEditForm.save()
            messages.success(request, "Event was successfully edited!")
            return redirect(reverse('eventplanning:plan'))
        else:
            messages.error(request, "Please enter valid data for the event!\nRemember that the Arrival Time must be equal or earlier than the Event Time!")
            eventEditForm = EventEditForm(instance=event, groups=groupQuerySet)
            return render(request, 'eventplanning/editevent.html', dictContext)

    elif request.method == "POST":
        messages.error(request, "You do not have permission to edit this event!")
        return redirect(reverse('eventplanning:plan'))

    elif not event in editableEvents:
        messages.error(request, "You do not have permission to edit this event!")
        return redirect(reverse('eventplanning:plan'))

    else:
        return render(request, 'eventplanning/editevent.html', dictContext)

@login_required
def attendEvent(request, id):
    title = 'User Management - Attend Event'
    groups = request.user.profile.commutegroup_set.all()
    userEvents = Event.objects.filter(group__in=groups, eventDate__gte=date.today())
    thisEvent = get_object_or_404(Event, id=id)
    initialDict = {'event': thisEvent}
    addrs = request.user.profile.address_set.all()

    attendeeCreationForm = AttendeeCreationForm(initial=initialDict, addrs=addrs)

    dictContext = {'title': title,'event': thisEvent, 'attendeeCreationForm': attendeeCreationForm}

    if request.method == "POST" and thisEvent in userEvents:
        
        attendeeCreationForm = AttendeeCreationForm(initial=initialDict, addrs=addrs, data=request.POST)
        
        if attendeeCreationForm.is_valid():
            attendedEvent = attendeeCreationForm.save(commit=False)
            attendedEvent.user = request.user.profile
            attendedEvent.save()

            messages.success(request, "You are now attending event " + thisEvent.name + "!")
            return redirect(reverse('eventplanning:home'))
        else:
            attendeeCreationForm = AttendeeCreationForm(initial=initialDict, addrs=addrs)
            return render(request, 'eventplanning/attevent.html', dictContext)

    elif request.method == "POST":
        messages.error(request, "You do not have permission to attend this event!")
        return redirect(reverse('eventplanning:home'))

    elif not thisEvent in userEvents:
        messages.error(request, "You do not have permission to attend this event!")
        return redirect(reverse('eventplanning:home'))

    else:
        return render(request, 'eventplanning/attevent.html', dictContext)

@login_required
def leaveEvent(request, id):
    title = 'User Management - Leave Event'
    event = get_object_or_404(Event, id=id)
    attendee = Attendee.objects.get(event=event, user=request.user.profile)

    if attendee:
        messages.success(request, "You are no longer attending event " + attendee.event.name + "!")
        attendee.delete()
        return redirect(reverse('eventplanning:home'))

    else:
        messages.error(request, "You do not have permission to modify attendance here!")
        return redirect(reverse('eventplanning:home'))

@login_required
def editAttendance(request, id):
    title = 'User Management - Edit Attendance'

    event = get_object_or_404(Event, id=id)
    attendee = Attendee.objects.get(event=event, user=request.user.profile)
    addrs = request.user.profile.address_set.all()

    attendeeCreationForm = AttendeeCreationForm(instance=attendee, addrs=addrs)
    dictContext = {'title': title,'event': event, 'attendeeCreationForm': attendeeCreationForm}

    if request.method == "POST" and attendee:
        attendeeCreationForm = AttendeeCreationForm(instance=attendee, addrs=addrs, data=request.POST)
        
        if attendeeCreationForm.is_valid():
            modifiedAttendee = attendeeCreationForm.save()
            messages.success(request, "Attendance successfully modified!")
            return redirect(reverse('eventplanning:home'))
        else:
            attendeeCreationForm = AttendeeCreationForm(instance=attendee, addrs=addrs)
            return render(request, 'eventplanning/attedit.html', dictContext)

    elif request.method == "POST":
        messages.error(request, "You do not have permission to edit this object!")
        return redirect(reverse('eventplanning:home'))

    elif attendee:
        attendeeCreationForm = AttendeeCreationForm(instance=attendee, addrs=addrs)
        return render(request, 'eventplanning/attedit.html', dictContext)

    else:
        messages.error(request, "You do not attend this event.")
        return redirect(reverse('eventplanning:home'))

django/data/eventplanning/templates/eventplanning/attedit.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Edit attendance to this event:</h1>
        <h2>{{ event }}</h2>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            <table>
                {{attendeeCreationForm.as_table}}
            </table>

            <input type="submit" value="Yes"/>
            <a href="{% url 'eventplanning:home' %}">Cancel </a>
        </form>
    </body>

{% endblock content %}

django/data/eventplanning/templates/eventplanning/attevent.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Attend this event:</h1>
        <h2>{{ event }}</h2>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            <table>
                {{attendeeCreationForm.as_table}}
            </table>
            
            <button type="submit" name="newAttendee" class="btn btn-default">Submit</button>
            <a href="{% url 'eventplanning:home' %}">Cancel</a>
        </form>
    </body>

{% endblock content %}

django/data/eventplanning/templates/eventplanning/delevent.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Delete this event:</h1>
        <h2>{{ event }}</h2>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            Are you sure you want to delete this event?</br>
            <input type="submit" value="Yes"/>
            <a href="{% url 'eventplanning:plan' %}">Cancel </a>
        </form>
    </body>

{% endblock content %}

django/data/eventplanning/templates/eventplanning/editevent.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Edit this event:</h1>
        <h2>{{ event }}</h2>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            <table>
                {{eventEditForm.as_table}}
            </table>

            <input type="submit" value="Yes"/>
            <a href="{% url 'eventplanning:plan' %}">Cancel </a>
        </form>
    </body>

{% endblock content %}

django/data/eventplanning/templates/eventplanning/home.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}
    <header>
        <h1>{{ title }}</h1>
        <p>posted by pmathy</p>
    </header>
    <body>
        <div>
            <h2>My Upcoming Events:</h1>
            {% for event in events %}
            <div>
                Event Name: {{ event.name }}<br>
                Event Date: {{ event.eventDate }}<br>
                Event Time: {{ event.eventTime }}<br>
                Arrival Time: {{ event.arrivalTime }}<br>
                {% if event in signedUpEvents %}
                    <a href="{% url 'eventplanning:attedit' event.id %}" >Edit Signup</a> | 
                    <a href="{% url 'eventplanning:leaveevent' event.id %}" >Sign out</a><br><br>
                {% else %}
                    <a href="{% url 'eventplanning:attevent' event.id %}" >Sign Up</a><br><br>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </body>
{% endblock content %}

django/data/eventplanning/templates/eventplanning/plan.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}
    <header>
        <h1>{{ title }}</h1>
        <p>posted by pmathy</p>
    </header>
    <body>
        <p>
            <h3>Create New Event:</h3>
            <a href='#' onclick='overlay()'>Create new Event</a>
        </p>
        <div>
            <h2>My editable Events:</h1>
            {% for event in events %}
            <div>
                Event Name: {{ event.name }}<br>
                Event Date: {{ event.eventDate }}<br>
                Event Time: {{ event.eventTime }}<br>
                Arrival Time: {{ event.arrivalTime }}<br>
                <a href="{% url 'eventplanning:editevent' event.id %}" >Edit Event</a> | 
                <a href="{% url 'routing:createroute' event.id %}" >Plan Route</a> | 
                <a href="{% url 'eventplanning:delevent' event.id %}" >Delete Event</a><br><br>
            </div>
            {% endfor %}
        </div>
        <div id="overlay">
            <div>
                <p>    
                    <form method="post" >
                        {% csrf_token %}
                        <table>
                            {{eventForm.as_table}}
                        </table><br><br>
                        <table>
                            {{destForm.as_table}}
                        </table>
                        
                        <button type="submit" name="newevent" onclick='overlay()' class="btn btn-default">Submit</button>
                        <a href="{% url 'eventplanning:plan' %}">Cancel</a>
                    </form>
                </p>
            </div>
        </div>
    </body>
{% endblock content %}