django/data/eventplanning/urls.py
from django.urls import path, re_path

from . import views

app_name = 'eventplanning'
urlpatterns = [
    path('home', views.home, name='home'),
    path('plan', views.plan, name='plan'),
    re_path(r'^del/event/(?P<id>.+)$', views.deleteEvent, name='delevent'),
    re_path(r'^edit/event/(?P<id>.+)$', views.editEvent, name='editevent'),
    re_path(r'^att/event/(?P<id>.+)$', views.attendEvent, name='attevent'),
    re_path(r'^attedit/event/(?P<id>.+)$', views.editAttendance, name='attedit'),
    re_path(r'^leave/event/(?P<id>.+)$', views.leaveEvent, name='leaveevent'),
]

django/data/project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = 'root'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('admin/', admin.site.urls),
    path('acc/', include('accounting.urls')),
    path('auth/', include('authentication.urls')),
    path('event/', include('eventplanning.urls')),
    path('route/', include('routing.urls')),
    path('usr/', include('usermanagement.urls'))
]

django/data/routing/urls.py
from django.urls import path, re_path

from . import views

app_name = 'routing'
urlpatterns = [
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)/(?P<passengerId>.+)$', views.deletePassenger, name='delpass'),
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)$', views.deleteVehicle, name='delcar'),
    re_path(r'^create/(?P<eventId>.+)$', views.createRoute, name='createroute'),
    re_path(r'^confirm/(?P<eventId>.+)$', views.confirmRoute, name='confirmroute'),
]

django/data/routing/models.py
from django.db import models

# Create your models here.

class Route(models.Model):
    event = models.OneToOneField("eventplanning.Event", on_delete=models.CASCADE, primary_key=True)
    isCompleted = models.BooleanField(default=False)
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Route to %s" % (self.event.name)

class Vehicle(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    driver = models.OneToOneField("eventplanning.Attendee", on_delete=models.CASCADE)

    def __str__(self):
        return "Vehicle for %s" % (self.route)

class Passenger(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    passenger = models.OneToOneField("eventplanning.Attendee", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "%s" % (self.passenger)

django/data/routing/forms.py
from django.forms.widgets import HiddenInput
from django.apps import apps
from django import forms
import re

from .models import Route, Vehicle, Passenger

class VehicleCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        drivers = kwargs.pop('drivers')
        super(VehicleCreationForm, self).__init__(*args, **kwargs)
        self.fields['route'].disabled=True
        self.fields['driver'] = forms.ModelChoiceField(
            queryset=drivers
        )
    class Meta:
        model = Vehicle
        fields = ['route', 'driver']

def createPassengerForm(passengers):
    class PassengerCreationForm(forms.ModelForm):
        def __init__(self, *args, **kwargs):
            super(PassengerCreationForm, self).__init__(*args, **kwargs)
            self.fields['vehicle'].disabled=True
            self.fields['vehicle'].widget = HiddenInput()

            self.fields['passenger'] = forms.ModelChoiceField(
                queryset=passengers
            )
        class Meta:
            model = Passenger
            fields = ['vehicle','passenger']

    return PassengerCreationForm
    

django/data/routing/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.apps import apps
from django.forms import modelformset_factory
from datetime import datetime

from .models import Route, Vehicle, Passenger
from .forms import VehicleCreationForm, createPassengerForm
from utils.utils import createMapsApiSrc as createApiString
from utils.utils import createLocations as createLocations
from utils.utils import createRoutes as createRoutes

# IMPORTANT!!! Still missing checks for permission on modifying the object.

@login_required
def createRoute(request, eventId):

    title = 'Route Creation'
    showNew = True
    apiString = createApiString("&callback=initMap")

    event = apps.get_model('eventplanning', 'Event').objects.get(id=eventId)
    route = event.route
    vehicles = route.vehicle_set.all()

    drivers = apps.get_model('eventplanning', 'Attendee').objects.filter(event=event, isDriver=True, isTaken=False)
    passengers = apps.get_model('eventplanning', 'Attendee').objects.filter(event=event, isTaken=False)

    initialCarDict = {'route': route}
    vehicleForm = VehicleCreationForm(initial=initialCarDict, drivers=drivers)
    formsetInstance = ()

    if vehicles: 
        for car in vehicles:
            if not car.passenger_set.all():
                showNew = False
                # initialize Passenger Form here
                slots = car.driver.slots
                initialPassDict = {'vehicle': car}
                initialPassList = []
                for i in range(slots):
                    initialPassList.append(initialPassDict)

                passengerCreationForm = createPassengerForm(passengers)
                PassengerFormSet = modelformset_factory(Passenger, form=passengerCreationForm, extra=slots)
                formsetInstance = PassengerFormSet(initial=initialPassList)

    locations = createLocations(event)
    driver_locs = locations['driver_loc']
    passenger_locs = locations['pass_loc']
    destination_locs = locations['dest_loc']
    if vehicles:
        routes = createRoutes(vehicles)
    else:
        routes = []
    arrivalTime = int((datetime.combine(event.eventDate, event.arrivalTime) - datetime(1970,1,1)).total_seconds())

    canFinish = True
    for attendee in event.attendee_set.all():
        if not attendee.isTaken:
            canFinish = False

    dictContext = {'title': title, 
        'event': event, 
        'vehicles': vehicles, 
        'vehicleForm': vehicleForm, 
        'formset': formsetInstance,
        'showNew': showNew,
        'apiString': apiString,
        'driver_locs': driver_locs,
        'passenger_locs': passenger_locs,
        'destination_locs': destination_locs,
        'routes': routes,
        'arrivalTime': arrivalTime,
        'canFinish': canFinish,
    }

    if request.method == "POST" and 'newvehicle' in request.POST:
        vehicleForm = VehicleCreationForm(initial=initialCarDict, drivers=drivers, data=request.POST)

        if vehicleForm.is_valid():
            driver = vehicleForm.cleaned_data['driver']
            driver.isTaken = True
            driver.save()

            vehicleInstance = vehicleForm.save()

            messages.success(request, str(driver) + " is now a driver and can be equipped with passengers.")
            return redirect(reverse('routing:createroute', kwargs={'eventId': eventId}))
        else:
            vehicleForm = VehicleCreationForm(initial=initialCarDict, drivers=drivers)
            return render(request, 'routing/createroute.html', dictContext)

    elif request.method == "POST" and 'newpassengers' in request.POST:
        formsetInstance = PassengerFormSet(initial=initialPassList, data=request.POST)

        if formsetInstance.is_valid():
            for form in formsetInstance:
                if form.cleaned_data:
                    attendee = form.cleaned_data['passenger']
                    attendee.isTaken = True
                    attendee.save()

            formsetInstance.save()

            messages.success(request, "Passengers were added successfully.")
            return redirect(reverse('routing:createroute', kwargs={'eventId': eventId}))
        else:
            formsetInstance = PassengerFormSet(initial=initialPassList)
            return render(request, 'routing/createroute.html', dictContext)

    else:
        return render(request, 'routing/createroute.html', dictContext)

@login_required
def deleteVehicle(request, eventId, vehicleId):
    vehicle = Vehicle.objects.get(id=vehicleId)
    vehicle.driver.isTaken = False
    vehicle.driver.save()

    for passenger in vehicle.passenger_set.all():
        passenger.passenger.isTaken = False
        passenger.passenger.save()

    vehicle.delete()
    messages.success(request, "Vehicle was successfully deleted.")

    return redirect(reverse('routing:createroute', kwargs={'eventId': eventId}))
    
@login_required    
def deletePassenger(request, eventId, vehicleId, passengerId):
    passenger = Passenger.objects.get(id=passengerId)
    passenger.passenger.isTaken = False
    passenger.passenger.save()
    passenger.delete()
    messages.success(request, "Passenger was successfully deleted.")

    return redirect(reverse('routing:createroute', kwargs={'eventId': eventId}))

@login_required
def confirmRoute(request, eventId):
    event = apps.get_model('eventplanning', 'Event').objects.get(id=eventId)
    route = event.route

    return redirect(reverse('eventplanning:plan'))

django/data/routing/templates/routing/createroute.html
{% extends 'afterLogin.html' %}

{% block mapsApi %}{{ apiString|safe }}{% endblock mapsApi %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <header>
        <h1>{{ title }}</h1>
        <p>posted by pmathy</p>
    </header>
    <body>
        <div id="map" style="width: 500px; height: 400px;"></div>
        {{ driver_locs|json_script:"driver_locs" }}
        {{ passenger_locs|json_script:"passenger_locs" }}
        {{ destination_locs|json_script:"destination_locs" }}
        {{ routes|json_script:"routes" }}
        {{ arrivalTime|json_script:"arrivalTime" }}
        <script type="text/javascript">
            const drive_locs = JSON.parse(document.getElementById('driver_locs').textContent);
            const pass_locs = JSON.parse(document.getElementById('passenger_locs').textContent);
            const dest_locs = JSON.parse(document.getElementById('destination_locs').textContent);
            const routes = JSON.parse(document.getElementById('routes').textContent);
            const arrivalTime = JSON.parse(document.getElementById('arrivalTime').textContent);
            createMap(drive_locs, pass_locs, dest_locs, routes, arrivalTime);
        </script>

        {% if showNew %}
            <p>
                <h3>Add new vehicle:</h3>
                <a href='#' onclick='overlay()'>Create new vehicle</a>
            </p>
        {% endif %}
        <div>
            {% if vehicles %}
                {% for car in vehicles %}
                    Driver: {{ car.driver }} | <a href="{% url 'routing:delcar' event.id car.id %}">Delete</a><br>
                    {% if car.passenger_set.all %}
                        Mitfahrer:<br>
                        {% for pass in car.passenger_set.all %}
                            {{ pass }} | <a href="{% url 'routing:delpass' event.id car.id pass.id %}">Delete</a><br>
                        {% endfor %}
                    {% else %}
                    <p>    
                        <form method="post" >
                            {% csrf_token %}
                            <table>
                                {{formset}}
                            </table>
                            <button type="submit" name="newpassengers" class="btn btn-default">Submit</button>
                            <a href="{% url 'routing:createroute' event.id %}">Cancel</a>
                        </form>
                    </p>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        {% if canFinish %}
            <p>
                <h3>Finish Route | Cancel</h3>
                <a href="{% url 'routing:confirmroute' event.id %}">Finish Routing</a> | <a href="{% url 'eventplanning:plan' %}">Cancel</a>
            </p>
        {% else %}
            <p>
                <h3>Cancel</h3>
                <a href="{% url 'eventplanning:plan' %}">Cancel</a>
            </p>
        {% endif %}
        <div id="overlay">
            <div>
                <p>    
                    <form method="post" >
                        {% csrf_token %}
                        <table>
                            {{vehicleForm.as_table}}
                        </table>
                        <button type="submit" name="newvehicle" onclick='overlay()' class="btn btn-default">Submit</button>
                        <a href="{% url 'routing:createroute' event.id %}">Cancel</a>
                    </form>
                </p>
            </div>
        </div>
    </body>
{% endblock content %}