django/data/project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = 'root'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('admin/', admin.site.urls),
    path('acc/', include('accounting.urls')),
    path('auth/', include('authentication.urls')),
    path('event/', include('eventplanning.urls')),
    path('route/', include('routing.urls')),
    path('usr/', include('usermanagement.urls'))
]

django/data/routing/urls.py
from django.urls import path, re_path

from . import views

app_name = 'routing'
urlpatterns = [
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)/(?P<passengerId>.+)$', views.deletePassenger, name='delpass'),
    re_path(r'^delete/(?P<eventId>.+)/(?P<vehicleId>.+)$', views.deleteVehicle, name='delcar'),
    re_path(r'^create/(?P<eventId>.+)$', views.createRoute, name='createroute'),
    re_path(r'^confirm/(?P<eventId>.+)$', views.confirmRoute, name='confirmroute'),
]

django/data/usermanagement/urls.py
from django.urls import path, re_path

from . import views

app_name = 'usrmgmt'
urlpatterns = [
    path('home', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('changepass', views.changePassword, name='changepass'),
    re_path(r'^del/addr/(?P<id>.+)$', views.deleteAddress, name='deladdr'),
    re_path(r'^del/grp/(?P<id>.+)$', views.deleteGroup, name='delgrp'),
    re_path(r'^adm/grp/(?P<id>.+)$', views.groupAdmin, name='admgrp'),
]

django/data/usermanagement/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField("authentication.CustomUser", on_delete=models.CASCADE, primary_key=True)
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email

class Address(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    city = models.CharField(max_length=30)
    street = models.CharField(max_length=30)
    postal = models.PositiveIntegerField()
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s, %s %s" % (self.street, self.postal, self.city)

class CommuteGroup(models.Model):
    name = models.CharField(max_length=30)
    member = models.ManyToManyField(Profile, blank=True)
    joinCode = models.CharField(max_length=10, default='None')
    
    timestamp_lastupdated = models.DateTimeField(auto_now=True)
    timestamp_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

django/data/usermanagement/forms.py
from django.apps import apps
from django import forms

from .models import CommuteGroup, Address, Profile
from utils.utils import verifyAddress as verifyAddress

class CommuteGroupCreationForm(forms.ModelForm):
    class Meta:
        model = CommuteGroup
        fields = ['name']

class AddressCreationForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street', 'postal', 'city']

    def clean(self):
        # Runs clean() method of ModelForm (parent Class) and verifies for 
        # Uniqueness etc.
        cleaned_data = super(AddressCreationForm, self).clean()
        
        if not verifyAddress(cleaned_data):
            raise forms.ValidationError(
                "This Address could not be found, please try again with a valid address."
            )

class JoinGroupForm(forms.Form):
    groupCodeField = forms.CharField(min_length=8, max_length=8, required=True,
    label='Join Code', help_text="Please enter the Join Code of the group you want to join.")

    def clean(self):
        # Runs clean() method of ModelForm (parent Class) and verifies for 
        # Uniqueness etc.
        cleaned_data = super(JoinGroupForm, self).clean()
        code=cleaned_data.get('groupCodeField')
        group = CommuteGroup.objects.filter(joinCode=code)

        if not group:
            raise forms.ValidationError(
                "This group code does not exist. Please check for errors."
            )

class ProfileEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        self.fields['email'].disabled=True
    class Meta:
        model = apps.get_model('authentication', 'CustomUser')
        fields = ['email','last_name','first_name']

class ChangePassForm(forms.Form):
    # Adds password and pw-confirm form fields as 'hidden' input
    oldPassword=forms.CharField(widget=forms.PasswordInput())
    newPassword=forms.CharField(widget=forms.PasswordInput())
    confirmNewPassword=forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(ChangePassForm, self).clean()
        newPassword = cleaned_data.get("newPassword")
        confirmNewPassword = cleaned_data.get("confirmNewPassword")

        if newPassword != confirmNewPassword:
            raise forms.ValidationError(
                "Password and confirmed password do not match."
            )

class MemberPermissionsForm(forms.Form):
    member = forms.CharField(required=False)
    adminPerm = forms.BooleanField()
    accountantPerm = forms.BooleanField()
    plannerPerm = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(MemberPermissionsForm, self).__init__(*args, **kwargs)
        self.fields['member'].disabled=True
    

django/data/usermanagement/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from django.contrib.auth import authenticate, login
from django.utils.crypto import get_random_string
from django.forms import formset_factory
from django.contrib import messages
from django.apps import apps
from string import ascii_uppercase, digits

from .forms import CommuteGroupCreationForm, AddressCreationForm, JoinGroupForm, ProfileEditForm, ChangePassForm, MemberPermissionsForm
from .utils import createPermissions
from .models import Address, CommuteGroup, Profile

# Create your views here.

@login_required
def home(request):
    title = 'User Management - Home'
    commGroups = request.user.profile.commutegroup_set.all()

    commgroupForm = CommuteGroupCreationForm()
    joinGroupForm = JoinGroupForm()

    dictContext = {'commgroupForm': commgroupForm, 'joinGroupForm': joinGroupForm,
        'title': title, 'commGroups': commGroups}

    if request.method == "POST" and 'newgroup' in request.POST:
        commgroupForm = CommuteGroupCreationForm(request.POST)

        if commgroupForm.is_valid():
            accName = 'acc_' + commgroupForm.cleaned_data['name']
            commgroupInstance = commgroupForm.save(commit=False)
            commgroupInstance.joinCode = get_random_string(8, ascii_uppercase + digits)
            commgroupInstance.save()

            commgroupInstance.member.add(request.user.profile)
            commgroupInstance.save()

            accName = 'Account_' + commgroupInstance.joinCode
            groupAccount = apps.get_model('accounting', 'Account')(name=accName, group=commgroupInstance)
            groupAccount.save()

            permissions = createPermissions(commgroupInstance.joinCode)
            

            for perm in permissions:
                request.user.user_permissions.add(permissions[perm])
                
            return redirect(reverse('usrmgmt:home'))
        else:
            commgroupForm = CommuteGroupCreationForm()
            return render(request, 'usermanagement/home.html', dictContext)

    elif request.method == "POST" and 'joingroup' in request.POST:
        joinGroupForm = JoinGroupForm(request.POST)

        if joinGroupForm.is_valid():
            code = joinGroupForm.cleaned_data['groupCodeField']
            group = CommuteGroup.objects.get(joinCode=code)

            group.member.add(request.user.profile)

            messages.success(request, "You have joined the group!")
            return redirect(reverse('usrmgmt:home'))
        else:
            messages.error(request, "Invalid")
            joinGroupForm = JoinGroupForm()
            return render(request, 'usermanagement/home.html', dictContext)
 
    else:

        return render(request, 'usermanagement/home.html', dictContext)

@login_required
def profile(request):
    title = 'User Management - Your Profile'
    
    addressList = []
    for address in request.user.profile.address_set.all():
        addressList.append(address)

    addressForm = AddressCreationForm()
    userForm = ProfileEditForm(instance=request.user)

    dictContext = {'addressForm': addressForm, 'userForm': userForm, 'title': title, 'addressList': addressList}

    if request.method == "POST" and 'newaddress' in request.POST:
        addressForm = AddressCreationForm(request.POST)

        if addressForm.is_valid():
            addressInstance = addressForm.save(commit=False)
            addressInstance.profile = request.user.profile
            addressInstance.save()
            return redirect(reverse('usrmgmt:profile'))
        else:
            messages.error(request, "This Address could not be found, please try again with a valid address.")
            addressForm = AddressCreationForm()
            return render(request, 'usermanagement/profile.html', dictContext)
    
    elif request.method == "POST" and 'changeduser' in request.POST:
        userForm = ProfileEditForm(instance=request.user, data=request.POST)

        if userForm.is_valid():
            userInstance = userForm.save()
            messages.success(request, "User Data was successfully modified!")
            return redirect(reverse('usrmgmt:profile'))
        else:
            messages.error(request, "User Modification failed, please check the data you entered.")
            userForm = ProfileEditForm(instance=request.user)
            return render(request, 'usermanagement/profile.html', dictContext)

    else: 
        return render(request, 'usermanagement/profile.html', dictContext)

@login_required
def deleteAddress(request, id):
    title = 'User Management - Delete Address'
    address = get_object_or_404(Address, id=id)

    dictContext = {'title': title,'address': address}

    if request.method == "POST" and request.user.profile == address.profile:
        address.delete()
        messages.success(request, "Address was successfully deleted!")
        return redirect(reverse('usrmgmt:profile'))

    elif request.method == "POST":
        messages.error(request, "You do not have permission to delete this address!")
        return redirect(reverse('usrmgmt:profile'))

    elif not request.user.profile == address.profile:
        messages.error(request, "You do not have permission to delete this address!")
        return redirect(reverse('usrmgmt:profile'))

    else:
        return render(request, 'usermanagement/deladdr.html', dictContext)

@login_required
def deleteGroup(request, id):
    title = 'User Management - Delete Group'
    group = get_object_or_404(CommuteGroup, id=id)
    adminPermName = 'admin_' + group.joinCode
    userPermissions = Permission.objects.filter(user=request.user)
    groupPermissions = Permission.objects.filter(name__icontains=group.joinCode)
    adminPerm = Permission.objects.get(name=adminPermName)

    dictContext = {'title': title,'group': group}

    if request.method == "POST" and adminPerm in userPermissions:
        group.delete()
        for perm in groupPermissions:
            perm.delete()

        messages.success(request, "Group was successfully deleted!")
        return redirect(reverse('usrmgmt:home'))

    elif request.method == "POST":
        messages.error(request, "You do not have permission to delete this group!")
        return redirect(reverse('usrmgmt:home'))

    elif adminPerm not in userPermissions:
        messages.error(request, "You do not have permission to delete this group!")
        return redirect(reverse('usrmgmt:home'))

    else:
        return render(request, 'usermanagement/delgrp.html', dictContext)

@login_required
def changePassword(request):
    title = 'User Management - Change Password'
    changePassForm = ChangePassForm()

    dictContext = {'title': title, 'changePassForm': changePassForm}

    if request.method == "POST":
        changePassForm = ChangePassForm(request.POST)

        if changePassForm.is_valid():
            username = request.user.email
            oldPassword = changePassForm.cleaned_data.get('oldPassword')
            newPassword = changePassForm.cleaned_data.get('newPassword')
            
            user = authenticate(username=username, password=oldPassword)

            if user:
                user.set_password(newPassword)
                user.save()
                login(request, user)
                messages.success(request, "Password was successfully changed!")
                return redirect(reverse('usrmgmt:profile'))

            else:
                messages.error(request, "Wrong password! Please provide correct authentication to change password.")
                return render(request, 'usermanagement/changepass.html', dictContext)
        else:
            changePassForm = ChangePassForm()
            messages.error(request, "Please make sure the new password and confirmed password match!")
            return render(request, 'usermanagement/changepass.html', dictContext)
    else:
        return render(request, 'usermanagement/changepass.html', dictContext)

# IMPORTANT!!! Still missing checks for permission on modifying the object.

@login_required
def groupAdmin(request, id):
    title = 'User Management - Administrate Group'

    group = CommuteGroup.objects.get(id=id)
    members = Profile.objects.filter(commutegroup=group).exclude(user=request.user)

    adminPermName = 'admin_' + group.joinCode
    accountantPermName = 'accountant_' + group.joinCode
    plannerPermName = 'planner_' + group.joinCode
    adminPerm = Permission.objects.get(name=adminPermName)
    accountantPerm = Permission.objects.get(name=accountantPermName)
    plannerPerm = Permission.objects.get(name=plannerPermName)

    initialData = []
    for member in members:
        memberPerms = Permission.objects.filter(name__icontains=group.joinCode, user=member.user)
        dataset = {}
        dataset['member'] = member.user.email
        dataset['adminPerm'] = False
        dataset['accountantPerm'] = False
        dataset['plannerPerm'] = False

        if adminPerm in memberPerms:
            dataset['adminPerm'] = True
        if accountantPerm in memberPerms:
            dataset['accountantPerm'] = True
        if plannerPerm in memberPerms:
            dataset['plannerPerm'] = True

        initialData.append(dataset)

    PermFormSet = formset_factory(MemberPermissionsForm, extra=0)
    formset = PermFormSet(initial=initialData)

    dictContext = {'title': title, 'group': group, 'formset': formset, 'init': initialData}

    if request.method == "POST":
        formset = PermFormSet(initial=initialData, data=request.POST)

        if formset.is_valid():
            for form in formset:
                user = apps.get_model('authentication', 'CustomUser').objects.get(email=form.cleaned_data['member'])

                if form.cleaned_data['adminPerm']:
                    user.user_permissions.add(adminPerm)
                else:

django/data/usermanagement/templates/usermanagement/admgrp.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>{{ group }}</h1>
        <h2>Group Member Administration</h2>
    </header>
    <body>
        <div>
            <form method="post" >
                {% csrf_token %}
                <table>
                    {{ formset }}
                </table>
                <input type="submit" value="Submit"/>
                <a href="{% url 'usrmgmt:home' %}">Cancel </a>
            </form>
        </div>
    </body>

{% endblock content %}

django/data/usermanagement/templates/usermanagement/changepass.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Change Password</h1>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            <table>
                {{changePassForm.as_table}}
            </table>
            <input type="submit" value="Yes"/>
            <a href="{% url 'usrmgmt:home' %}">Cancel </a>
        </form>
    </body>

{% endblock content %}

django/data/usermanagement/templates/usermanagement/deladdr.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Delete this address:</h1>
        <h2>{{ address }}</h2>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            Are you sure you want to delete this address?</br>
            <input type="submit" value="Yes"/>
            <a href="{% url 'usrmgmt:profile' %}">Cancel </a>
        </form>
    </body>

{% endblock content %}

django/data/usermanagement/templates/usermanagement/delgrp.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}

    <header>
        <h1>Delete this group:</h1>
        <h2>{{ group }}</h2>
    </header>
    <body>
        <form method="post" >
            {% csrf_token %}
            Are you sure you want to delete this group?</br>
            <input type="submit" value="Yes"/>
            <a href="{% url 'usrmgmt:home' %}">Cancel </a>
        </form>
    </body>

{% endblock content %}

django/data/usermanagement/templates/usermanagement/home.html
{% extends 'afterLogin.html' %}
{% load global_extras %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}
    <header>
        <h1>{{ title }}</h1>
        <p>posted by pmathy</p>
    </header>
    <body>
        <div>
            <h2>My Groups:</h1>
            {% for group in commGroups %}
            <div>
                Group Name: {{ group.name }}<br>
                Group Join Code: {{ group.joinCode }}<br>
                {% if group.joinCode|addstr:".admin_"|addstr:group.joinCode in perms %}
                    <a href="{% url 'usrmgmt:delgrp' group.id %}" >Delete Group</a> | 
                    <a href="{% url 'usrmgmt:admgrp' group.id %}" >Group Admin</a>
                {% endif %}
                <br><br>
            </div>
            {% endfor %}
        </div>
        <p>
            <h3>Join Group:</h3>
            <form method="post" >
                {% csrf_token %}
                <table>
                    {{ joinGroupForm.as_table }}
                </table>
                
                <button type="submit" name="joingroup" class="btn btn-default">Submit</button>
            </form>
        </p>
        <p>
            <h3>Create Group:</h3>
            <a href='#' onclick='overlay()'>Create new Commute Group</a>
        </p>
        <div id="overlay">
            <div>
                <p>    
                    <form method="post" >
                        {% csrf_token %}
                        <table>
                            {{commgroupForm.as_table}}
                        </table>
                        
                        <button type="submit" name="newgroup" onclick='overlay()' class="btn btn-default">Submit</button>
                        <a href="{% url 'usrmgmt:profile' %}">Cancel</a>
                    </form>
                </p>
            </div>
        </div>
    </body>
{% endblock content %}

django/data/usermanagement/templates/usermanagement/profile.html
{% extends 'afterLogin.html' %}

{% block title %}{{ title }}{% endblock title %}
 
{% block content %}
    <header>
        <h1>{{ title }}</h1>
        <p>posted by pmathy</p>
    </header>
    <body>
        <div>
            <p>    
                <form method="post" >
                    {% csrf_token %}
                    <table>
                        {{userForm.as_table}}
                    </table>
                    
                    <button type="submit" name="changeduser" class="btn btn-default">Submit</button>
                    <a href="{% url 'usrmgmt:profile' %}">Cancel</a>
                </form>
            </p>
            <a href="{% url 'usrmgmt:changepass' %}">Change Password</a>
        </div>
        <div>
            <h2>My Addresses:</h1>
            {% for address in addressList %}
            <div>
                {{ address }}
                <a href="{% url 'usrmgmt:deladdr' address.id %}" >Delete this Address</a>
            </div>
            {% endfor %}
        </div>
        <p>
            <a href='#' onclick='overlay()'>Add new Address</a>
        </p>
        <div id="overlay">
            <div>
                <p>    
                    <form method="post" >
                        {% csrf_token %}
                        <table>
                            {{addressForm.as_table}}
                        </table>
                        
                        <button type="submit" name="newaddress" onclick='overlay()' class="btn btn-default">Submit</button>
                        <a href="{% url 'usrmgmt:profile' %}">Cancel</a>
                    </form>
                </p>
            </div>
        </div>
    </body>
{% endblock content %}